// This file is automatically generated by Aether CSS Modules
// Do not edit this file directly

export const a: string;

interface CSSModuleClasses {
  readonly a: string;
}

declare const classes: CSSModuleClasses;
export default classes;