// This file is automatically generated by Aether CSS Modules
// Do not edit this file directly

export const b: string;

interface CSSModuleClasses {
  readonly b: string;
}

declare const classes: CSSModuleClasses;
export default classes;