// This file is automatically generated by Aether CSS Modules
// Do not edit this file directly

export const button: string;

interface CSSModuleClasses {
  readonly button: string;
}

declare const classes: CSSModuleClasses;
export default classes;