// This file is automatically generated by Aether CSS Modules
// Do not edit this file directly

export const app: string;

interface CSSModuleClasses {
  readonly app: string;
}

declare const classes: CSSModuleClasses;
export default classes;