import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'jsx-runtime': 'src/jsx-runtime.ts',
    'jsx-dev-runtime': 'src/jsx-dev-runtime.ts',
    index: 'src/index.ts',
    'core/index': 'src/core/index.ts',
    'core/reactivity/index': 'src/core/reactivity/index.ts',
    'core/component/index': 'src/core/component/index.ts',
    'di/index': 'src/di/index.ts',
    'modules/index': 'src/modules/index.ts',
    'router/index': 'src/router/index.ts',
    'forms/index': 'src/forms/index.ts',
    'control-flow/index': 'src/control-flow/index.ts',
    'primitives/index': 'src/primitives/index.ts',
    'server/index': 'src/server/index.ts',
    'devtools/index': 'src/devtools/index.ts',
    'cli/index': 'src/cli/index.ts',
    'netron/index': 'src/netron/index.ts',
    'store/index': 'src/store/index.ts',
    'data/index': 'src/data/index.ts',
    'suspense/index': 'src/suspense/index.ts',
    'suspense/server': 'src/suspense/server.ts',
    'i18n/index': 'src/i18n/index.ts',
    'styling/index': 'src/styling/index.ts',
    'theming/index': 'src/theming/index.ts',
    'compiler/index': 'src/compiler/index.ts',
    'testing/index': 'src/testing/index.ts',
    'build/index': 'src/build/index.ts',
    'build/vite-plugin': 'src/build/vite-plugin.ts',
    // Styled Components
    'components/forms/index': 'src/components/forms/index.ts',
    'components/data/index': 'src/components/data/index.ts',
    'components/layout/index': 'src/components/layout/index.ts',
    'components/navigation/index': 'src/components/navigation/index.ts',
    'components/interactive/index': 'src/components/interactive/index.ts',
    'components/feedback/index': 'src/components/feedback/index.ts',
    'components/overlay/index': 'src/components/overlay/index.ts',
    'components/utility/index': 'src/components/utility/index.ts',
    'components/editor/index': 'src/components/editor/index.ts',
    // Icon presets (stroke, duotone, twotone)
    'svg/icons/presets/index': 'src/svg/icons/presets/index.ts',
    'svg/icons/presets/stroke/index': 'src/svg/icons/presets/stroke/index.ts',
    'svg/icons/presets/duotone/index': 'src/svg/icons/presets/duotone/index.ts',
    'svg/icons/presets/twotone/index': 'src/svg/icons/presets/twotone/index.ts',
  },
  format: ['esm'],
  dts: false, // Temporarily disabled due to TSX circular dependency with jsx-runtime types
  sourcemap: true,
  clean: true,
  splitting: false,
  treeshake: true,
  minify: false,
  target: 'es2022',
  outDir: 'dist',
  tsconfig: './tsconfig.json',
  external: [
    '@omnitron-dev/netron-browser',
    '@omnitron-dev/aether/jsx-runtime',
    '@omnitron-dev/aether/jsx-dev-runtime',
    'typescript',
    'vite',
    'ws',
    'fs',
    'path',
    'crypto',
    'stream',
    'node:stream',
  ],
  esbuildOptions(options) {
    // Allow jsx-runtime imports to be resolved after build
    options.alias = {
      '@omnitron-dev/aether/jsx-runtime': './jsx-runtime.js',
      '@omnitron-dev/aether/jsx-dev-runtime': './jsx-dev-runtime.js',
    };
  },
});
