/**
 * The torrc an onion service runs on, and why each line is in it.
 *
 * Built here rather than by shell inside the container. The previous version
 * assembled it with `cat`, `jq` and a `while read` loop at runtime, which
 * meant the one file that decides whether a service is anonymous could not
 * be read without starting a container, and could not be tested at all. A
 * hardening option that is silently dropped by a quoting mistake looks
 * exactly like one that was never asked for.
 *
 * Everything here is a real Tor option, checked against `tor --version`
 * 0.4.9.12 — the newest in Alpine 3.21, measured rather than assumed.
 *
 * The threat this is written against: an adversary who wants to learn which
 * host runs the service, or to make it stop. Not an adversary who has the
 * host — that one has the keys, and no torrc helps.
 */

export interface TorHiddenService {
  /** Directory name under /var/lib/tor, and the name `omnitron tor` prints. */
  name: string;
  /** Port clients reach on the .onion address. */
  virtualPort: number;
  /** `host:port` tor forwards plaintext to. */
  target: string;
  /**
   * Public keys allowed to reach this service, as `<name>:descriptor:x25519:<base32>`.
   *
   * v3 client authorization, and the strongest privacy control an onion
   * service has: without a listed key a client cannot decrypt the
   * descriptor, so the service is not merely closed to them — it is
   * undiscoverable. The cost is that every legitimate client needs the
   * matching private key installed, so it is off unless asked for.
   */
  authorizedClients?: string[] | undefined;
}

export interface TorrcInputs {
  services: readonly TorHiddenService[];
  /** Appended verbatim, last, so an operator can always have the final word. */
  extra?: readonly string[] | undefined;
}

/**
 * Per-service defence tuning.
 *
 * The introduction point is where an onion service is cheapest to attack:
 * anyone can ask it to relay an introduction, and the service pays to
 * answer. These are the two mechanisms Tor gives for that, and neither is
 * on by default.
 */
const INTRO_DOS_RATE_PER_SEC = 25;
const INTRO_DOS_BURST_PER_SEC = 200;
/** PoW: how fast the service dequeues client requests, and the burst it tolerates. */
const POW_QUEUE_RATE = 250;
const POW_QUEUE_BURST = 2500;
/** A single client's streams on one rendezvous circuit. */
const MAX_STREAMS_PER_CIRCUIT = 128;

export function renderTorrc(inputs: TorrcInputs): string {
  const lines: string[] = [
    '# =====================================================================',
    '# Onion-service-only Tor, generated by omnitron. Do not edit in place —',
    '# the container rewrites this file on every start.',
    '# =====================================================================',
    '',
    '# Identity. Tor drops privileges to this account after binding.',
    'User tor',
    '',
    '# --- This process is not a relay, not a proxy, and not a client ------',
    '#',
    '# A SOCKS port would make the host an open proxy on its docker network;',
    '# an ORPort would make it a relay, which publishes its address in the',
    '# consensus — the one fact an onion service exists to withhold.',
    'SocksPort 0',
    'ORPort 0',
    'DirPort 0',
    'ControlPort 0',
    'ClientOnly 1',
    'ExitRelay 0',
    'ExitPolicy reject *:*',
    'ExitPolicy reject6 *:*',
    'BridgeRelay 0',
    'PublishServerDescriptor 0',
    '',
    '# --- Anonymity ------------------------------------------------------',
    '#',
    '# Single-hop mode trades the service\'s anonymity for latency. It is off',
    '# by default and named here so that turning it on is a visible edit and',
    '# not an omission.',
    'HiddenServiceSingleHopMode 0',
    'HiddenServiceNonAnonymousMode 0',
    '',
    '# Guard discovery is the attack that finds the host behind an onion',
    '# service: watch which relays it builds circuits through, narrow the',
    '# set, then attack what is left. Tor 0.4.7+ keeps layer-2 and layer-3',
    '# guards for onion services automatically (vanguards-lite) — this',
    '# states the entry layer it rests on.',
    'UseEntryGuards 1',
    'NumEntryGuards 1',
    'EnforceDistinctSubnets 1',
    '',
    '# Padding hides the shape of traffic from whoever can see the link to',
    '# the guard. The reduced variants exist for battery-powered clients and',
    '# cost anonymity; a server has no reason to take that trade.',
    'ConnectionPadding 1',
    'ReducedConnectionPadding 0',
    'CircuitPadding 1',
    'ReducedCircuitPadding 0',
    '',
    '# IPv4 only. A host reachable both ways is two chances to be correlated,',
    '# and onion traffic needs neither.',
    'ClientUseIPv4 1',
    'ClientUseIPv6 0',
    'ClientPreferIPv6ORPort 0',
    '',
    '# --- What is written down -------------------------------------------',
    '#',
    '# SafeLogging scrubs addresses from the log. `notice` is the highest',
    '# level that never logs a circuit or a stream: `info` and `debug` do,',
    '# and a debug log from an onion service is a deanonymisation waiting to',
    '# be read by whoever gets the file.',
    'SafeLogging 1',
    'Log notice stdout',
    'LogTimeGranularity 1000',
    'LogMessageDomains 0',
    '',
    '# Nothing about this service belongs on disk beyond its keys.',
    'DataDirectory /var/lib/tor',
    'DataDirectoryGroupReadable 0',
    'AvoidDiskWrites 1',
    'RunAsDaemon 0',
    '',
    '# --- Process hardening ----------------------------------------------',
    '#',
    '# NoExec stops tor executing anything at all, which removes the class',
    '# of bug where a malformed input becomes a command. DisableDebugger-',
    '# Attachment keeps another process on the host from reading the keys',
    '# out of memory.',
    'NoExec 1',
    'DisableDebuggerAttachment 1',
    'HardwareAccel 1',
    '',
  ];

  for (const service of inputs.services) {
    lines.push(
      `# --- Hidden service: ${service.name} ---`,
      `HiddenServiceDir /var/lib/tor/${service.name}`,
      // v3 only. v2 was removed from Tor, and its addresses were 80-bit
      // truncated hashes — brute-forceable to a lookalike.
      'HiddenServiceVersion 3',
      `HiddenServicePort ${service.virtualPort} ${service.target}`,
      '',
      '# The introduction point is where this service is cheapest to attack:',
      '# anyone may ask it to relay an introduction, and the service pays to',
      '# answer. Neither defence is on by default.',
      'HiddenServiceEnableIntroDoSDefense 1',
      `HiddenServiceEnableIntroDoSRatePerSec ${INTRO_DOS_RATE_PER_SEC}`,
      `HiddenServiceEnableIntroDoSBurstPerSec ${INTRO_DOS_BURST_PER_SEC}`,
      'HiddenServicePoWDefensesEnabled 1',
      `HiddenServicePoWQueueRate ${POW_QUEUE_RATE}`,
      `HiddenServicePoWQueueBurst ${POW_QUEUE_BURST}`,
      '',
      '# One client must not be able to hold the service open indefinitely.',
      `HiddenServiceMaxStreams ${MAX_STREAMS_PER_CIRCUIT}`,
      'HiddenServiceMaxStreamsCloseCircuit 1',
      '',
      '# The key directory is this service. Group-readable means any process',
      '# in the container s group can copy the identity.',
      'HiddenServiceDirGroupReadable 0',
    );

    if (service.authorizedClients && service.authorizedClients.length > 0) {
      lines.push(
        '',
        `# ${service.authorizedClients.length} authorized client(s): without one of`,
        '# these keys a client cannot decrypt the descriptor, so the service',
        '# is not merely closed to them — it is undiscoverable.',
      );
    }

    lines.push('');
  }

  if (inputs.extra && inputs.extra.length > 0) {
    lines.push('# --- Operator additions ---', ...inputs.extra, '');
  }

  return lines.join('\n');
}

/**
 * The `.auth` files that make client authorization real.
 *
 * Returned separately from the torrc because they are not torrc lines: tor
 * reads them from `<HiddenServiceDir>/authorized_clients/`, and a key that
 * never reaches that directory is a restriction that silently does not
 * exist.
 */
export function authorizedClientFiles(
  services: readonly TorHiddenService[],
): Array<{ path: string; content: string }> {
  const files: Array<{ path: string; content: string }> = [];

  for (const service of services) {
    for (const [index, key] of (service.authorizedClients ?? []).entries()) {
      files.push({
        path: `/var/lib/tor/${service.name}/authorized_clients/client-${index + 1}.auth`,
        content: `${key}\n`,
      });
    }
  }

  return files;
}
