[test]
# Test configuration for Bun
preload = []
coverage = true
coverageReporter = ["text", "lcov"]

[install]
# Package installation settings
auto = "auto"
frozenLockfile = false
globalBinDir = "~/.bun/bin"

[run]
# Runtime configuration
silent = false