FROM keymetrics/omnitron:latest

RUN mkdir -p /var/app

WORKDIR /var/app

COPY ./package.json /var/app
RUN npm install
## DEVELOPMENT MODE
ENV NODE_ENV=development
CMD ["omnitron-dev", "process.json", "--env", "development"]