#!/sbin/openrc-run
# Copyright 2013-2022 the OMNITRON project authors. All rights reserved.
# Init script automatically generated by omnitron startup

description="Production process manager for Node.js apps with a built-in load balancer."

extra_started_commands="reload"

OMNITRON="%OMNITRON_PATH%"
user=${OMNITRON_USER:-%USER%}
export OMNITRON_HOME=$(eval echo ~${user})"/.omnitron/"
# Options for start-stop-daemon (default start function)
command=${OMNITRON}
command_user=${user}
command_args="resurrect"
pidfile=${OMNITRON_HOME}/omnitron.pid

run_omnitron_as_user() {
	einfo "${OMNITRON} $@"
	eval su -l ${user} -c \'${OMNITRON} $@\'
}

depend() {
	need net
	need localmount
	after bootmisc
}

start_post() {
	if [ "${user}" == "root" ]; then
		ewarn "OMNITRON: Better run this daemon as a non root user. To set this user create"
		ewarn "OMNITRON: /etc/conf.d/omnitron file and define 'OMNITRON_USER=user' there."
		ewarn "OMNITRON: Note user MUST have home directory for OMNITRON logs/state/etc..."
	fi
	einfo "OMNITRON: Process Manager started. To start services run:"
	einfo "OMNITRON: # su -l ${user} -c '$OMNITRON start /path/to/app'"
}

stop() {
	ebegin "Stopping OMNITRON process manager..."
	run_omnitron_as_user dump
	run_omnitron_as_user kill
	eend $?
}

reload() {
	ebegin "Reloading omnitron"
	run_omnitron_as_user reload all
	eend $?
}

# vim: ts=4
