# Meridian Configuration File
# Cognitive memory system for LLM codebase interaction

[index]
# Languages to index
languages = ["rust", "typescript", "javascript", "python", "go", "markdown"]

# Paths/patterns to ignore
ignore = [
    "node_modules",
    "target",
    ".git",
    "dist",
    "build",
    ".next",
    "coverage",
    ".cache"
]

# Maximum file size to index
max_file_size = "1MB"

[storage]
# Path to store the index
path = ".meridian/index"

# Cache size for hot data
cache_size = "256MB"

[memory]
# Days to retain episodic memories
episodic_retention_days = 30

# Size of working memory
working_memory_size = "10MB"

# Interval for memory consolidation
consolidation_interval = "1h"

[session]
# Maximum number of concurrent sessions
max_sessions = 10

# Session timeout (idle time before auto-cleanup)
session_timeout = "1h"

[monorepo]
# Automatically detect projects in monorepo
detect_projects = true

# File markers that indicate a project root
project_markers = [
    "Cargo.toml",
    "package.json",
    "tsconfig.json",
    "go.mod",
    "pyproject.toml",
    "pom.xml"
]

[learning]
# Minimum episodes needed to extract a pattern
min_episodes_for_pattern = 3

# Confidence threshold for pattern recognition
confidence_threshold = 0.7

[mcp]
# Unix socket path for MCP server (optional)
# Leave empty to use stdio only
socket = "/tmp/meridian.sock"

# Maximum tokens in a single response
max_token_response = 2000

# HTTP/SSE transport configuration
[mcp.http]
# Enable HTTP transport
enabled = true

# Server host (bind address)
host = "127.0.0.1"

# Server port
port = 3000

# CORS allowed origins (use ["*"] for all origins in development)
cors_origins = ["*"]

# Maximum concurrent connections
max_connections = 100
