/**
 * Gateway Config Generator
 *
 * Auto-generates nginx/openresty configuration from the ecosystem's
 * app transport definitions. Replaces manually maintained nginx.conf files.
 *
 * Reads app bootstrap configs to determine transport ports, then generates:
 * - Upstream blocks (round-robin for scaled apps)
 * - Location blocks (path-based routing per service)
 * - CORS headers, WebSocket upgrade support
 * - Rate limiting zones
 * - SSL termination config (if certs are configured)
 *
 * Output: Complete nginx.conf content ready to write to disk or pipe to nginx.
 */

import type { IEcosystemConfig, IEcosystemAppEntry } from '../config/types.js';

// =============================================================================
// Types
// =============================================================================

export interface GatewayConfig {
  /** Listen port for the gateway (default: 8080) */
  listenPort: number;
  /** Listen host (default: 0.0.0.0) */
  listenHost: string;
  /** Server name for nginx server_name directive */
  serverName: string;
  /** Enable CORS headers */
  cors: boolean;
  /** SSL certificate path (enables HTTPS if set) */
  sslCert?: string;
  /** SSL key path */
  sslKey?: string;
  /** Rate limit zone (requests per second) */
  rateLimit?: number;
  /** Custom nginx directives to include */
  customDirectives?: string[];
}

export interface AppRoute {
  /** App name */
  name: string;
  /** Upstream host:port */
  upstream: string;
  /** URL path prefix (default: /api/<name>) */
  pathPrefix: string;
  /** Number of instances (for upstream weight) */
  instances: number;
  /** Whether the app supports WebSocket */
  websocket: boolean;
  /** WebSocket path (if different from HTTP) */
  wsPath?: string | undefined;
}

// =============================================================================
// Default Config
// =============================================================================

const DEFAULT_GATEWAY: GatewayConfig = {
  listenPort: 8080,
  listenHost: '0.0.0.0',
  serverName: '_',
  cors: true,
};

/** Default port map — mirrors apps/omnitron/src/config/defaults.ts */
const DEFAULT_PORTS: Record<string, number> = {
  main: 3001,
  storage: 3002,
  priceverse: 3003,
  paysys: 3004,
  messaging: 3005,
};

// =============================================================================
// Route Extraction
// =============================================================================

/**
 * Extract routes from ecosystem app entries.
 * Reads bootstrap configs to determine HTTP/WS ports.
 */
export function extractAppRoutes(apps: IEcosystemAppEntry[]): AppRoute[] {
  const routes: AppRoute[] = [];

  for (const app of apps) {
    if (app.enabled === false) continue;

    const port = DEFAULT_PORTS[app.name] ?? 3000;

    routes.push({
      name: app.name,
      upstream: `127.0.0.1:${port}`,
      pathPrefix: `/api/${app.name}`,
      instances: app.instances ?? 1,
      websocket: app.name === 'messaging', // Messaging uses WebSocket
      wsPath: app.name === 'messaging' ? `/ws/${app.name}` : undefined,
    });
  }

  return routes;
}

// =============================================================================
// Nginx Config Generation
// =============================================================================

/**
 * Generate complete nginx.conf from ecosystem configuration.
 *
 * @param apps Ecosystem app entries
 * @param ecosystemConfig Full ecosystem config (for daemon ports, etc.)
 * @param gatewayConfig Optional gateway-specific overrides
 * @returns Complete nginx.conf content
 */
export function generateGatewayConfig(
  apps: IEcosystemAppEntry[],
  _ecosystemConfig: IEcosystemConfig,
  gatewayConfig?: Partial<GatewayConfig>
): string {
  const config = { ...DEFAULT_GATEWAY, ...gatewayConfig };
  const routes = extractAppRoutes(apps);
  const lines: string[] = [];

  // Header
  lines.push('# Auto-generated by Omnitron Gateway Generator');
  lines.push(`# Generated at: ${new Date().toISOString()}`);
  lines.push('# Do NOT edit manually — changes will be overwritten.');
  lines.push('');

  // Worker config
  lines.push('worker_processes auto;');
  lines.push('error_log /var/log/nginx/error.log warn;');
  lines.push('pid /var/run/nginx.pid;');
  lines.push('');
  lines.push('events {');
  lines.push('    worker_connections 4096;');
  lines.push('    multi_accept on;');
  lines.push('}');
  lines.push('');

  // HTTP block
  lines.push('http {');
  lines.push('    include /etc/nginx/mime.types;');
  lines.push('    default_type application/octet-stream;');
  lines.push('');
  lines.push('    # Performance');
  lines.push('    sendfile on;');
  lines.push('    tcp_nopush on;');
  lines.push('    tcp_nodelay on;');
  lines.push('    keepalive_timeout 65;');
  lines.push('    keepalive_requests 1000;');
  lines.push('');
  lines.push('    # Logging');
  lines.push('    log_format main \'$remote_addr - $remote_user [$time_local] "$request" \'');
  lines.push('                    \'$status $body_bytes_sent "$http_referer" \'');
  lines.push('                    \'"$http_user_agent" "$http_x_forwarded_for" \'');
  lines.push('                    \'rt=$request_time urt=$upstream_response_time\';');
  lines.push('    access_log /var/log/nginx/access.log main;');
  lines.push('');

  // Rate limiting
  if (config.rateLimit) {
    lines.push(`    # Rate limiting — ${config.rateLimit} req/s per client IP`);
    lines.push(`    limit_req_zone $binary_remote_addr zone=api:10m rate=${config.rateLimit}r/s;`);
    lines.push('');
  }

  // Upstream blocks
  lines.push('    # ============================================================');
  lines.push('    # Upstreams — auto-generated from app transport definitions');
  lines.push('    # ============================================================');
  lines.push('');

  for (const route of routes) {
    lines.push(`    upstream ${route.name}_backend {`);
    for (let i = 0; i < route.instances; i++) {
      const host = route.upstream.split(':')[0];
      const basePort = parseInt(route.upstream.split(':')[1]!, 10);
      const port = route.instances > 1 ? basePort + i : basePort;
      lines.push(`        server ${host}:${port};`);
    }
    lines.push('        keepalive 32;');
    lines.push('    }');
    lines.push('');
  }

  // Omnitron daemon upstream (for console webapp)
  lines.push('    upstream omnitron_backend {');
  lines.push(`        server 127.0.0.1:9800;`); // DEFAULT_DAEMON_CONFIG.httpPort
  lines.push('        keepalive 16;');
  lines.push('    }');
  lines.push('');

  // Server block
  lines.push('    # ============================================================');
  lines.push('    # Server — main entry point');
  lines.push('    # ============================================================');
  lines.push('');
  lines.push('    server {');

  // Listen directive
  if (config.sslCert && config.sslKey) {
    lines.push(`        listen ${config.listenHost}:${config.listenPort} ssl http2;`);
    lines.push(`        ssl_certificate ${config.sslCert};`);
    lines.push(`        ssl_certificate_key ${config.sslKey};`);
    lines.push('        ssl_protocols TLSv1.2 TLSv1.3;');
    lines.push('        ssl_ciphers HIGH:!aNULL:!MD5;');
    lines.push('        ssl_prefer_server_ciphers on;');
    lines.push('        ssl_session_cache shared:SSL:10m;');
    lines.push('        ssl_session_timeout 10m;');
  } else {
    lines.push(`        listen ${config.listenHost}:${config.listenPort};`);
  }

  lines.push(`        server_name ${config.serverName};`);
  lines.push('');

  // Security headers
  lines.push('        # Security headers');
  lines.push("        add_header X-Frame-Options DENY always;");
  lines.push("        add_header X-Content-Type-Options nosniff always;");
  lines.push("        add_header X-XSS-Protection '1; mode=block' always;");
  lines.push("        add_header Referrer-Policy strict-origin-when-cross-origin always;");
  lines.push('');

  // CORS
  if (config.cors) {
    lines.push('        # CORS');
    lines.push("        add_header Access-Control-Allow-Origin '*' always;");
    lines.push("        add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;");
    lines.push("        add_header Access-Control-Allow-Headers 'Authorization, Content-Type, X-Request-ID' always;");
    lines.push("        add_header Access-Control-Max-Age 86400 always;");
    lines.push('');
    lines.push('        if ($request_method = OPTIONS) {');
    lines.push("            return 204;");
    lines.push('        }');
    lines.push('');
  }

  // App location blocks
  lines.push('        # ========================================================');
  lines.push('        # API routes — auto-generated from app definitions');
  lines.push('        # ========================================================');
  lines.push('');

  for (const route of routes) {
    lines.push(`        # ${route.name}`);
    lines.push(`        location ${route.pathPrefix}/ {`);
    lines.push(`            proxy_pass http://${route.name}_backend/;`);
    lines.push('            proxy_set_header Host $host;');
    lines.push('            proxy_set_header X-Real-IP $remote_addr;');
    lines.push('            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;');
    lines.push('            proxy_set_header X-Forwarded-Proto $scheme;');
    lines.push('            proxy_http_version 1.1;');
    lines.push("            proxy_set_header Connection '';");

    if (config.rateLimit) {
      lines.push(`            limit_req zone=api burst=${config.rateLimit * 2} nodelay;`);
    }

    lines.push('        }');
    lines.push('');

    // WebSocket location
    if (route.websocket && route.wsPath) {
      lines.push(`        location ${route.wsPath}/ {`);
      lines.push(`            proxy_pass http://${route.name}_backend/;`);
      lines.push('            proxy_http_version 1.1;');
      lines.push("            proxy_set_header Upgrade $http_upgrade;");
      lines.push("            proxy_set_header Connection 'upgrade';");
      lines.push('            proxy_set_header Host $host;');
      lines.push('            proxy_set_header X-Real-IP $remote_addr;');
      lines.push('            proxy_read_timeout 86400s;');
      lines.push('            proxy_send_timeout 86400s;');
      lines.push('        }');
      lines.push('');
    }
  }

  // Omnitron Console
  lines.push('        # Omnitron Console (webapp + RPC)');
  lines.push('        location /omnitron/ {');
  lines.push('            proxy_pass http://omnitron_backend/;');
  lines.push('            proxy_set_header Host $host;');
  lines.push('            proxy_set_header X-Real-IP $remote_addr;');
  lines.push('            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;');
  lines.push('            proxy_set_header X-Forwarded-Proto $scheme;');
  lines.push('            proxy_http_version 1.1;');
  lines.push("            proxy_set_header Connection '';");
  lines.push('        }');
  lines.push('');

  // Health check endpoint
  lines.push('        # Health check');
  lines.push('        location /health {');
  lines.push("            return 200 'ok';");
  lines.push("            add_header Content-Type text/plain;");
  lines.push('        }');
  lines.push('');

  // Default: serve Omnitron Console SPA
  lines.push('        # Default: Omnitron Console SPA');
  lines.push('        location / {');
  lines.push('            proxy_pass http://omnitron_backend/;');
  lines.push('            proxy_set_header Host $host;');
  lines.push('            proxy_set_header X-Real-IP $remote_addr;');
  lines.push('            proxy_http_version 1.1;');
  lines.push("            proxy_set_header Connection '';");
  lines.push('        }');

  // Custom directives
  if (config.customDirectives?.length) {
    lines.push('');
    lines.push('        # Custom directives');
    for (const directive of config.customDirectives) {
      lines.push(`        ${directive}`);
    }
  }

  lines.push('    }'); // server
  lines.push('}'); // http
  lines.push('');

  return lines.join('\n');
}
