/**
 * Six apps were given `postgres:postgres` against a generated secret.
 *
 * The config a master writes onto a node listed the apps, their bootstrap
 * paths and the stack to run them in — and no `infrastructure` block, because
 * the master has nothing to put there: `provisionStack` runs
 * `withGeneratedCredentials` against the NODE's vault, so a stack that
 * declares no password has none for the master to know.
 *
 * `resolveStackAddresses` reads that block and nothing else when it builds
 * `DATABASE_URL`, `REDIS_URL` and the S3 variables, and its fallback for an
 * absent one is not an error:
 *
 *     const defaultPgPassword =
 *       infra?.postgres?.password ?? getEnv().POSTGRES_PASSWORD ?? 'postgres';
 *
 * Measured on the test node, all six apps at once:
 *
 *     Database connection default failed after 5 retries:
 *     password authentication failed for user "postgres" (28P01)
 *
 * — against `daos-test-postgres`, whose own 43-character generated password
 * answers over TCP. On a laptop that same fallback is CORRECT: a local stack
 * with no declared password really does use `postgres`. That is why nothing
 * caught it until a stack with generated credentials ran somewhere else, and
 * why the fix supplies the addresses rather than removing the fallback.
 *
 * Two halves of one description, each authoritative for its own: the master
 * decides WHAT the stack is — services, ports, databases, buckets — and the
 * node decides what the SECRETS are, because they are generated by its own
 * vault and exist nowhere else.
 *
 * **The addresses go in each app's `env`, and never in an `infrastructure`
 * block.** Writing one was the first attempt and it cost more than the
 * problem: a stack with an infrastructure block is a stack the node
 * PROVISIONS, so the node autostarted its own `deployed` stack, built a
 * second complete set of containers under `daos-deployed-*` on empty volumes,
 * and swept the master's `daos-test-*` away as orphans. An address is not an
 * instruction to build what it points at, and the two must not be said with
 * one sentence.
 */

import { describe, it, expect } from 'vitest';

import { overlayCredentials } from '../../src/infrastructure/node-credentials.js';
import { renderNodeAppConfig } from '../../src/project/node-app-config.js';

const GENERATED = 'Xk3p9QzR7tLmN2vB8cF4wJ6hY1sD5gA0eU-iO_pT3qZ';

describe('the node knows the secrets and the master knows the shape', () => {
  it('takes the password from the node and the port from the stack', () => {
    const out = overlayCredentials(
      { postgres: { port: 5432, user: 'postgres', password: 'postgres', databases: { geo: { migrate: true } } } },
      { postgres: { host: 'localhost', port: 9999, user: 'postgres', password: GENERATED } },
    ) as { postgres: Record<string, unknown> };

    expect(out.postgres['password']).toBe(GENERATED);
    // The node's port is NOT taken: it carried out the stack's decision and
    // letting its answer win would make a node's drift authoritative.
    expect(out.postgres['port']).toBe(5432);
    expect(out.postgres['databases']).toEqual({ geo: { migrate: true } });
  });

  it('takes both of minio\'s secrets and neither of its addresses', () => {
    const out = overlayCredentials(
      { minio: { ports: { api: 9000 }, accessKey: 'minioadmin', secretKey: 'minioadmin', buckets: ['storage'] } },
      { minio: { endpoint: 'http://localhost:9000', accessKey: 'AK' + GENERATED, secretKey: 'SK' + GENERATED } },
    ) as { minio: Record<string, unknown> };

    expect(out.minio['accessKey']).toBe('AK' + GENERATED);
    expect(out.minio['secretKey']).toBe('SK' + GENERATED);
    expect(out.minio['buckets']).toEqual(['storage']);
    expect(out.minio['ports']).toEqual({ api: 9000 });
  });

  it('leaves a service the node could not answer for exactly as declared', () => {
    const declared = { postgres: { port: 5432, password: 'declared-secret' }, redis: { port: 6379 } };
    const out = overlayCredentials(declared, { postgres: { password: GENERATED } }) as Record<
      string,
      Record<string, unknown>
    >;

    expect(out['postgres']!['password']).toBe(GENERATED);
    expect(out['redis']).toEqual({ port: 6379 });
  });

  it('does not invent a service nobody declared', () => {
    // `getConnectionInfo` answers for anything it has configured. An answer
    // about something this stack did not ask to provision is not evidence
    // that it should exist in the stack's config.
    const out = overlayCredentials({ postgres: { port: 5432 } }, { minio: { accessKey: 'AK', secretKey: 'SK' } });

    expect(Object.keys(out!)).toEqual(['postgres']);
  });

  it('refuses an empty answer rather than blanking a real secret', () => {
    const out = overlayCredentials(
      { postgres: { password: 'declared-secret' } },
      { postgres: { password: '' } },
    ) as { postgres: Record<string, unknown> };

    expect(out.postgres['password']).toBe('declared-secret');
  });

  it('does not modify what it was given', () => {
    const declared = { postgres: { port: 5432, password: 'old' } };
    overlayCredentials(declared, { postgres: { password: GENERATED } });

    expect(declared.postgres.password).toBe('old');
  });

  it('says nothing about a stack with no infrastructure at all', () => {
    expect(overlayCredentials(undefined, { postgres: { password: GENERATED } })).toBeUndefined();
  });
});

describe('the config written onto the node carries what the apps connect to', () => {
  const base = {
    project: 'daos',
    artifactRoot: '/opt/omnitron/artifacts',
    apps: [{ name: 'geo', script: 'src/main.ts', env: { LOG_LEVEL: 'info' } }] as never,
    artifacts: [{ app: 'geo', version: '0.0.1' }],
  };

  const parse = (body: string) => JSON.parse(body.slice(body.indexOf('{'), body.lastIndexOf('}') + 1));

  it('puts the resolved addresses in the app\'s own env', () => {
    const body = renderNodeAppConfig({
      ...base,
      appEnv: { geo: { DATABASE_URL: `postgres://postgres:${GENERATED}@localhost:5432/geo` } },
    });

    expect(parse(body).apps[0].env.DATABASE_URL).toBe(`postgres://postgres:${GENERATED}@localhost:5432/geo`);
  });

  it('never writes an infrastructure block', () => {
    // The first attempt at this wrote one, and a stack with an
    // infrastructure block is a stack the node PROVISIONS: the node
    // autostarted its own `deployed` stack, built a second complete set of
    // containers under `daos-deployed-*` on empty volumes, and swept the
    // master's `daos-test-*` as orphans. An address is not an instruction to
    // build what it points at.
    const body = renderNodeAppConfig({
      ...base,
      appEnv: { geo: { DATABASE_URL: 'postgres://u:p@localhost:5432/geo' } },
    });

    expect('infrastructure' in parse(body)).toBe(false);
    expect(body).not.toContain('"infrastructure"');
  });

  it('keeps the app\'s declared env and lets the resolved value win', () => {
    // The declaration was written without knowing which machine it would
    // land on; the resolved value was computed against what is actually
    // running there.
    const body = renderNodeAppConfig({
      ...base,
      apps: [{ name: 'geo', env: { LOG_LEVEL: 'info', DATABASE_URL: 'postgres://dev:dev@localhost/geo' } }] as never,
      appEnv: { geo: { DATABASE_URL: 'postgres://u:real@localhost:5432/geo' } },
    });

    const env = parse(body).apps[0].env;
    expect(env.LOG_LEVEL).toBe('info');
    expect(env.DATABASE_URL).toBe('postgres://u:real@localhost:5432/geo');
  });

  it('leaves an app alone when nothing was resolved for it', () => {
    const body = renderNodeAppConfig({ ...base, appEnv: { other: { DATABASE_URL: 'x' } } });
    expect(parse(body).apps[0].env).toEqual({ LOG_LEVEL: 'info' });
  });

  it('warns the reader that the file holds credentials', () => {
    // The file was written 0644 for as long as it has existed. That was
    // harmless only while it held nothing worth reading.
    const body = renderNodeAppConfig({ ...base, appEnv: { geo: { DATABASE_URL: 'postgres://u:p@h/db' } } });
    expect(body).toMatch(/CONTAINS CREDENTIALS/);
    expect(body).toMatch(/0600/);
  });

  it('still lists the apps and their stack', () => {
    const body = renderNodeAppConfig(base);
    const parsed = parse(body);

    expect(parsed.apps.map((a: { name: string }) => a.name)).toEqual(['geo']);
    expect(parsed.stacks.deployed.apps).toEqual(['geo']);
  });
});
